---
title: "DATA 608 Final Project Proposal"
author: "Ilya Kats"
date: "March 25, 2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background

Since the threat by the White House to cut the funding to the National Endowment for the Arts (NEA) last year, I have explored the subject of the arts in several projects within this data science program. I consider arts to be an integral part in what makes us human and as such think that it should be a critical part of primary and secondary education.

In the early 2000s New York City Depart of Education (NYCDOE) developed a curriculum framework for what students should know, understand, and be able to achieve in dance, music, theater and visual arts. Starting from 2007 NYCDOE has issues an annual survey to provide accountability for arts education that results in the _Annual Arts in Schools Report_. The system-wide report includes data about arts teachers, arts budgeting, space for the arts, partnerships with arts and cultural organizations, and parent involvement for elementary, middle, and high schools. 

The report is managed by Office of Arts & Special Projects (OASP). More information is available at  http://schools.nyc.gov/offices/teachlearn/arts/arts-count/annual-reporta.html.

## Objective

The report generated by OASP includes a lot of descriptive information and multiple charts comparing current results with past performance. However, it lacks any kind of geographical analysis (with the exception of high-level comparison of 5 boroughs). The goal of the final project is to plot available data on top of a NYC map. Since there are various subjects, the tentative plan is to create an interactive applicatio (using either Shiny or Dash). Since it is a system-wide program it is possible that there is not much variation by school (perhaps, each school gets enough funding for 1-2 arts teachers and that's it). However, I believe this is worth analyzing a bit further.

## Data

The latest report (PDF) is available at the OASP site: http://schools.nyc.gov/offices/teachlearn/arts/files/ArtsCount/2016-17%20Annual_Arts_in_Schools_Report_FINAL.pdf.

Data (in Excel) and data dictionary for the most recent survey (2016-2017 year) can be downloaded from the following page: http://schools.nyc.gov/offices/teachlearn/arts/arts-count/annual-reporta.html. Data is also provided on NYC Open Data site (https://data.cityofnewyork.us/Education/2016-2017-Arts-Survey-Data/ujyk-wix4). 

Finally, a list of schools can be downloaded in Excel format from NYCDOE site (http://schools.nyc.gov/Offices/EnterpriseOperations/DIIT/OOD/default.htm). This list provides additional information about the schools including school address that can be used to generate mapping coordinates.

_**"Art is a nation's most precious heritage. For it is in our works of art that we reveal to ourselves and to others the inner vision which guides us as a nation. And where there is no vision, the people perish."**_ - Lyndon Johnson, on signing into existence NEA

_P.S. The latest budget includes a small increase in NEA's funding._